version: '3'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: kapraokai/my-frontend_image:1.0
    ports:
      - "3000:3000"
    command: ["yarn", "dev"]