version: '3'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: kapraokai/my-frontend_image:1.0
    ports:
      - '3000:8080'
    volumes:
      - .:/app
    command: ["yarn", "dev"]
